CZWOW_NPCText_count=6;CZWOW_NPCText_6={
["ifiwereyou,i'dbuyagoblinracevoucher.rootingfortheotherteamisawasteoftime."]="Být tebou, já bych koupil závodní los na skřítka. Sazet na jiný tým je ztráta času. ",
["youlookingforplucky?well,youdidn'thearmesaythis,but...maybeifyouaskkronkriderupinthetower,he'lltellyou..."]="Hledas nejakou odvaznou praci?  Fajn, neslysel jsi mne toto rici, ale... mozna pokud by ses zeptal Kronkridera nahore ne vezi, rekl by ti to...",
["iinstalledanewdeviceinourcar'smatrixregulometer.thatshouldincreaseitsvelocityquotientbyafactorofnolessthanfifteen!"]="Instaloval jsem nové zařízení do našeho vozu tzv : \"matrixový regulometr\". To by mělo zvětšit její rychlostní kvocient více než patnáctinásobně!",
["plucky?iheardracemasterkronkrideruponthethetowerknowswhereheis."]="Plucky? Slyšel jsem, že pan Kronkrider nahoře na věži ví, kde by mohl být.",
["lookin'totakeagryphonride,eh?dungarkeepshisbirdsupontherampartinthetradedistrict.justremembertoholdontight!"]="Vy chcete na gryfu jezdit, co? Dungar vede jeho ptaky az na val v obchodní oblasti (Trade District). Jen nezapomente drzet na nohou!",
["ahhh,stormwindvisitor'scenteriswhatyouarelookingforthen.it'sthefirstbuildingontheleftasyouwalkthroughthefrontgatesfromthevalleyofheroes."]="Ahhh, potřebuješ jít do Stormwindského Návštěvního Centra. Je to první budova na levé straně když procházíš branami z Údolí Hrdinů.",
["soundslikeyouwanttotalktomaginordumas!youcanusuallyfindhiminthewizard'ssanctuminthemagequarter.course,youneverknowwhenorwherethosemagiwillportaloffto."]="Zní to jako bys chtěl mluvit s Maginor Dumas! Ty ho můžete najít v Průvodcové Svatyni v Mage Čtvrti. Kurs, nezjistíš  když mág protál má pryč.",
["oldtowniswhereyoushouldgoifyouwanttofindrogues.it'sinthenortheastcornerofstormwind."]="Staré město je to pravé místo když chceš najít nějkého zloděje.",
["achildofnaturearewe?thenyouneedlooknofurtherthenthemoonwellinthepark."]="Jsme děti přírody? Potom by ses měl porozhédnout kolem měsíční studny nedaleko v Parku.",
["iwouldsuggestlookinginthecathedraloflightincathedralsquare."]="Doporučil bych ti podívat se do Katedrály Světel na Katedrálním Náměstí.",
["whohasthefastestcar?whoknows?!?"]="Kdo má nejrychlejší auto? Kdo ví?!?",
["justbrowsingmywaresoristheresomethingspecificicanhelpyoufindtoday?"]="Pouze si prohlížíš mé zboží nebo hledáš něco konkrétního, s čím bych ti mohl pomoci?",
["wouldyourathertrustyourgoodswithagoblin?"]="Vy byste poněkud důvěřovali vašemu zboží s šotkem?",
["mymaster,pluggerspazzring,isagoodboss.andhemakesalotofmoney.hispocketsarebursting!"]="Můj pán, Plugger Spazzring, je dobrý šéf.A dává mi hodně peněz. Jeho kapsy praskají penězi!",
["ithinkpluggerfilledoneofhiskegstoomuch.itlookslikeit'sabouttoblow!"]="Myslím si že Plugger naplnil jeden z jeho sudu až moc. Vypadá to, že asi bouchne!",
["atlast,mysoulisfree!"]="Konečně, moje duše je zachráněna!",
["that'srightfriend!thedarkmoonfaireisgoingtoberighthere.justassoonasiunloadthosehugewagons,putupallthetents,erectthezooandpourthedrinks.makesureyoucomeback!"]="To je pravda příteli!  Darkmoon Faire bude stát tady. Hned jak vyložíme ty obrovské vozy, postavíme všechny stany, vystavíme ZOO tak budem nalévat nápoje. Ujistuje tě, ať se vrátíš!",
["iwishyouahappyholiday,friend!"]="Přeji vám šťastné svátky, příteli!",
["andyouwouldbe?"]="A vy by jste mohli?",
["yes?whatdoyouwant?"]="Ano? Co chceš?",
["idon'thavetimetotalkrightnow."]="Máš čas si popovídat teď?",
};if not CZWOW_NPCText then CZWOW_NPCText=0; end; CZWOW_NPCText=CZWOW_NPCText+21;
